# Generated by Django 4.2.11 on 2025-05-01 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='google_map_link',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='yandex_map_link',
        ),
    ]
