# Generated by Django 5.2.1 on 2025-05-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_client_address_alter_client_driverlicense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive'), ('Blacklisted', 'Blacklisted')], default='Active', max_length=11),
        ),
    ]
